### ISSUE TITLE
Not a real issue - Tumblr hashtags 

### ISSUE THREAD

**Issue by joehatfield94** [ScriptSmith/reaper#11]
Hi, 

My name is Joe Hatfield, and I am a graduate student at the University of Colorado Boulder. First off, thank you so much for developing this tool; it has been a lifesaver for my research. Does the tool scrape for ALL hashtags included on individual Tumblr posts? In other words, is there a column(s) for additional hashtags included in a post other than the one used to scrape? My csv seems not to include that info, but I was wondering if perhaps I was missing it. 

Many thanks,

Joe

**Comment by joehatfield94** [comment]
Nevermind - I see now that I did not have the "primary key" option enabled.

**Comment by ScriptSmith** [comment]
Just a note - the other hashtags used in a post are in the `tags` columns
