### ISSUE TITLE
dont have access public repository

### ISSUE THREAD

**Issue by raulshum** [ScriptSmith/reaper#7]
when i tried to install the package.. i got the error..

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q git@github.com:ScriptSmith/socialreaper.git /home/localadmin/reaper/src/socialreaper" failed with error code 128 in None

**Comment by ScriptSmith** [comment]
This should be fixed now

**Comment by raulshum** [comment]
nope same error.  tried on two machines.  ubuntu 16.04 lts

**Comment by ScriptSmith** [comment]
I just tried

```
docker run -it ubuntu:16.04 /bin/bash
```

Then

```
apt-get update && apt-get install -y python3-pip git
git clone https://github.com/ScriptSmith/reaper.git
cd reaper
pip3 install -r requirements.txt
```

It ran perfectly fine.

Are you sure that you cloned / pulled the repo after my commit? And are you sure the error was _exactly_ the same?

If your copy had my commit, it shouldn't say `git@github.com:ScriptSmith/socialreaper.git` anywhere in the error

**Comment by raulshum** [comment]
i tried your commands.. i get the following..

root@56ab20489d84:/reaper# python3 reaper.py
  File "reaper.py", line 57
    self.window.setWindowTitle(f"Reaper {self.version}")
                                                      ^
SyntaxError: invalid syntax

I'm running this on Linux mint 18.2 XFCE

**Comment by ScriptSmith** [comment]
As stated in the README, you need to use Python 3.6, make sure that's the version you're running.

You don't need to run Reaper in Docker, I was just mimicking the environment you're using.
